TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += chtobisr.db
DB += chtobisr_status.db
DB += chtobisr_faults.db
DATA += chtobisr.proto

#=======================================
include $(TOP)/configure/RULES
