TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += chtobisr.db
DATA += chtobisr.proto

#=======================================
include $(TOP)/configure/RULES
